
--DROP TABLE POSTO;
--DROP TABLE VACINA;
--DROP TABLE POSTOVACINA;

CREATE TABLE POSTO 
(	
	ID INT IDENTITY (1,1),
	NOME VARCHAR (60) UNIQUE NOT NULL ,
	PRIMARY KEY (ID)	
)

CREATE TABLE VACINA 
(	
	ID INT IDENTITY (1,1),
	NOME VARCHAR (60) UNIQUE NOT NULL,
	PRIMARY KEY (ID)	
)

CREATE TABLE POSTOVACINA 
(
	
	ID INT IDENTITY (1,1),
	IDPOSTO INT NOT NULL,
	IDVACINA INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	FOREIGN KEY (IDPOSTO) REFERENCES POSTO(ID),
    FOREIGN KEY (IDVACINA) REFERENCES VACINA(ID)

)